name: gds
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
permissions:
  contents: write
  pages: write
  id-token: write
env:
  CACHE_NUMBER: 3
jobs:
  xls:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: cache conda
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-${{ env.CACHE_NUMBER }}-conda-${{ hashFiles('environment.yml') }}
    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        activate-environment: tinytapeout
        channel-priority: strict
        environment-file: environment.yml
        use-only-tar-bz2: true
    - name: update path
      shell: bash -l {0}
      run: |
        echo $CONDA/envs/tinytapeout/bin >> $GITHUB_PATH
    - name: run dslx test
      run: |
        cat << EOF >> $GITHUB_STEP_SUMMARY
        # test
        \`\`\`
        `interpreter_main src/user_module.x 2>&1`
        \`\`\`
        EOF
    - name: generate rtl
      run: |
        ir_converter_main --top=user_module src/user_module.x > src/user_module.ir
        opt_main src/user_module.ir > src/user_module_opt.ir
        codegen_main --module_name user_module --use_system_verilog=false --generator=combinational src/user_module_opt.ir > src/user_module.v
        sed -i -e 's/wire \[7:0\] out/wire \[7:0\] io_out/' src/user_module.v
        sed -i -e 's/assign out =/assign io_out =/' src/user_module.v

    - name: add verilog to summary
      run: |
        cat << EOF >> $GITHUB_STEP_SUMMARY
        # codegen
        \`\`\`
        `cat src/user_module.v`
        \`\`\`
        EOF
    - name: populate rtl cache
      uses: actions/cache@v3
      with:
        path: |
          src/user_module.x
          src/user_module.ir
          src/user_module_opt.ir
          src/user_module.v
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-rtl-${{ github.run_id }}
  
  gds:
    needs:
    - xls
    env:
        OPENLANE_IMAGE_NAME:    efabless/openlane:2022.07.02_01.38.08
        OPENLANE_ROOT:  /home/runner/openlane
        PDK_ROOT:       /home/runner/pdk
        PDK:            sky130B

    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3

    # build PDK and fetch OpenLane

    - name: pdk & caravel
      run: |
        cd $HOME
        git clone https://github.com/efabless/caravel_user_project.git -b mpw-7a
        cd caravel_user_project
        make setup

    # need python
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install requests PyYAML

    # restore generated rtl
    - name: restore rtl cache
      uses: actions/cache@v3
      with:
        path: |
          src/user_module.x
          src/user_module.ir
          src/user_module_opt.ir
          src/user_module.v
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-rtl-${{ github.run_id }}

    # fetch the Verilog from Wokwi API
    - name: fetch Verilog and build config
      run: ./configure.py --create-user-config

    # run OpenLane to build the GDS
    - name: make GDS
      run: >
        docker run --rm
        -v $OPENLANE_ROOT:/openlane
        -v $PDK_ROOT:$PDK_ROOT
        -v $(pwd):/work
        -e PDK_ROOT=$PDK_ROOT
        -u $(id -u $USER):$(id -g $USER)
        $OPENLANE_IMAGE_NAME
        /bin/bash -c "./flow.tcl -verbose 2 -overwrite -design /work/src -run_path /work/runs -tag wokwi"

    # for debugging, show all the files
    - name: show files
      run: find runs/wokwi/

    # print some routing stats
    - name: add summary
      run: ./configure.py --get-stats >> $GITHUB_STEP_SUMMARY

    # print some cell stats
    - name: cell usage summary
      run: |
        git clone https://github.com/TinyTapeout/sssummarizer
        sssummarizer/sssummarizer.py --gl runs/wokwi/results/final/verilog/gl/*.v --print-category >> $GITHUB_STEP_SUMMARY

    - name: populate src cache
      uses: actions/cache@v3
      with:
        path: src
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-src-${{ github.run_id }}

    - name: populate runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-runs-${{ github.run_id }}

  svg:
    needs: gds
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: restore runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-runs-${{ github.run_id }}

    - name: create svg
      run: |
        python -m pip install gdstk
        python << EOF
        import gdstk
        import pathlib

        gds = sorted(pathlib.Path('runs').glob('wokwi/results/final/gds/*.gds'))
        library = gdstk.read_gds(gds[-1])
        top_cells = library.top_level()
        top_cells[0].write_svg('gds_render.svg')
        EOF

    - name: populate svg cache
      uses: actions/cache@v3
      with:
        path: 'gds_render.svg'
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-svg-${{ github.run_id }}

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    steps:
    - name: checkout GDS2glTF repo
      uses: actions/checkout@v3
      with:
        repository: mbalestrini/GDS2glTF

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: restore runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-runs-${{ github.run_id }}

    - name: gds2gltf
      run: |
        python -m pip install numpy gdspy triangle pygltflib
        cp runs/wokwi/results/final/gds/*.gds tinytapeout.gds
        python3 gds2gltf.py tinytapeout.gds

    - name: populate viewer cache
      uses: actions/cache@v3
      with:
        path: 'tinytapeout.gds.gltf'
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-viewer-${{ github.run_id }}

  commit:
    needs:
    - gds
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: restore rtl cache
      uses: actions/cache@v3
      with:
        path: |
          src/user_module.x
          src/user_module.ir
          src/user_module_opt.ir
          src/user_module.v
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-rtl-${{ github.run_id }}

    - name: commit generated rtl
      run: |
        git config --local user.name "tinybot"
        git config --local user.email "bot@tinytapeout.com"
        git add src/
        git commit -m "src: generated user module [skip ci]" || true
        git push origin main
    
  artifact:
    needs:
    - gds
    runs-on: ubuntu-latest
    steps:
    - name: restore src cache
      uses: actions/cache@v3
      with:
        path: src
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-src-${{ github.run_id }}

    - name: restore runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-runs-${{ github.run_id }}

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          # path depends on the tag and the module name
          name: GDS
          path: |
            src/*
            runs/wokwi/results/final/*
            runs/wokwi/reports/metrics.csv
            runs/wokwi/reports/synthesis/1-synthesis.AREA 0.stat.rpt

  pages:
    needs:
    - svg
    - viewer
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: restore svg cache
      uses: actions/cache@v3
      with:
        path: 'gds_render.svg'
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-svg-${{ github.run_id }}
    - name: restore viewer cache
      uses: actions/cache@v3
      with:
        path: 'tinytapeout.gds.gltf'
        key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-viewer-${{ github.run_id }}
    - name: generate redirect to viewer
      run: |
        cat << EOF >> index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Redirecting to GDS Viewer...</title>
          </head>
          <body>
            <script>
              location.href = "https://gds-viewer.tinytapeout.com/?model=" + encodeURIComponent(location.href + '/tinytapeout.gds.gltf');
            </script>
          </body>
          </html>
        EOF
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '.'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1.2.2

  preview:
    needs: pages
    runs-on: ubuntu-latest
    steps:
    - name: add gds preview
      run: |
        PAGE_URL=${{ needs.pages.outputs.page_url }}
        PAGE_URL=$(echo "$PAGE_URL" | sed -e 's/\/$//')
        cat << EOF >> $GITHUB_STEP_SUMMARY
        # layout
        ![svg]($PAGE_URL/gds_render.svg)
        # viewer
        [open preview](https://gds-viewer.tinytapeout.com/?model=$PAGE_URL/tinytapeout.gds.gltf)
        EOF
